### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/slippery#1]
We need refactoring in decorators:

- [ ] `@efficiency`
- [ ] `@disassemble`
- [ ] `@execution_time`
- [ ] `@prettify`

**Comment by FarmerSez** [comment]
@lk-geimfari, What in your mind is needed to be done? I think it's only a little bit cluttered, but all in all the code is fine.

**Comment by lk-geimfari** [comment]
@FarmerSez Okay. Just general refactoring.
