### ISSUE TITLE
Function name, code line and params in output of efficiency

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/slippery#3]
We need to add function name, code line and `*args`, `**kwargs` to output of `@efficiency`.

**Comment by virresh** [comment]
Hello, 
I would like to take this up.

**Comment by lk-geimfari** [comment]
@virresh Okay! Thanks!

**Comment by virresh** [comment]
Should this be closed now @lk-geimfari  ?
Or something else we need to add in the @efficiency decorator ?
