### ISSUE TITLE
Simplify output templates

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/slippery#5]
Output templates looks really awful.We should simplify it, because it's looks unreadable

```python
OUTPUT_TEMPLATE = BLUE_LINES + '''
\033[1mTotal time\033[0m: \033[92m{time:0.8f} Sec\033[0m.
\033[1mCalled function\033[0m: \033[92m{func}({args}, {kwargs}\033[92m)\033[0m\n
\033[1mResult\033[0m: \033[92m{result}\033[0m.
''' + BLUE_LINES
```

We need to fix it.

**Comment by janczer** [comment]
I would like do it.

To simplify it I should use functions in file `output.py` like `bold` etc?

**Comment by lk-geimfari** [comment]
@janczer Please, look at this issue for first: #6

**Comment by leofigs** [comment]
I think this was already fixed in another issue, no?

**Comment by lk-geimfari** [comment]
@leofigs Yeah, it was fixed.
