### ISSUE TITLE
Add function for colorized strings.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/slippery#6]
We have created function for all different colors:

```python
bold("Message")
green("Message")
```
Should be:

```python
clr(message, 'g') # where g is green
```

**Comment by viveksyngh** [comment]
I will take this up

**Comment by lk-geimfari** [comment]
@viveksyngh Nice! Let me know if you have any questions. Thanks!

**Comment by viveksyngh** [comment]
Seems like this is already handled in #10

**Comment by viveksyngh** [comment]
But different functions like blue, green, cyan are being used at different places .. should not we remove them and use color_line everywhere ?
