### ISSUE TITLE
Add function shortened().

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/slippery#7]
Some function return large data structures and we need to shorten them for output:

```python
>>> shortened({x for x in range(1000)})
>>> '{1, 2, 3, ...}'

>>> shortened([x for x in range(1000)])
>>> '[1, 2, 3, ...]'
```

**Comment by R4wm** [comment]
https://github.com/lk-geimfari/slippery/pull/8

**Comment by lk-geimfari** [comment]
@R4wm Please, look at comment.

**Comment by swapsha96** [comment]
I guess, we should close this issue.
